### ISSUE TITLE
Stop getting results

### ISSUE THREAD

**Issue by olymk2** [cosmicexplorer/helm-rg#26] opened 2020-06-12 07:47 UTC
So recently I have stopped getting results, not sure if this is due to an updated package or something, is there a nice way to debug why i get no results ?

manually moving to the folder in a shell and writing out the command from helm-rg works. 

```
$ emacs --version
GNU Emacs 26.3

```

```
$ /usr/bin/rg --version
ripgrep 12.1.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

```

![image](https://user-images.githubusercontent.com/1034950/84476719-7bc00b80-ac86-11ea-9527-a5255d4160e7.png)

**Comment by hankmander** [comment] 2020-06-13 13:32
I recently ran into the same issue and it seems to be that helm-rg is incompatible with the latest version of helm. I downgraded to helm 3.6.1 and it worked again: https://github.com/emacs-helm/helm/releases/tag/v3.6.1

**Comment by TimQuelch** [comment] 2020-06-14 23:49
I just did a bisect of helm and it appears to have broken in https://github.com/emacs-helm/helm/commit/4071dca7f80b590a9d089ff790fb54224fad110d

**Comment by olymk2** [comment] 2020-06-15 07:27
@hankmander thanks for that info, guessing that means helm-rg needs to be patched to the newer helm, or is it a bug in helm ? I will try downgrading for now anyway.

**Comment by TimQuelch** [comment] 2020-06-15 07:44
I suspect it is something to do with this change here

https://github.com/emacs-helm/helm/commit/4071dca7f80b590a9d089ff790fb54224fad110d#diff-8c8f72d1065ad18ee00c7ada381eb897R1567-R1578

but I'm not too sure tbh

**Comment by olymk2** [comment] 2020-06-15 13:36
I just noticed there is a PR open which might be related https://github.com/cosmicexplorer/helm-rg/pull/25

**Comment by seokbeomKim** [comment] 2020-06-15 17:59
@olymk2 Yes it is. I've just tested that this issue has been solved after applying the PR code.

**Comment by cosmicexplorer** [comment] 2020-07-21 07:29
I really appreciate the involved investigation here to solve a problem I'd been having a lot of difficulty with!! As of #25 being merged, I believe @braineo has fixed the issue as confirmed above by @seokbeomKim (thank you!!). Thank you also to @olymk2 for the very very detailed bug description!

Please reopen this issue if this failure recurs, or another issue for any new failures ^_^

**Closed by cosmicexplorer** 2020-07-21 07:29 UTC
